In [89]:
from xbbg import blp
import pdblp
import yfinance as yf
import pandas as pd

In [78]:
T0 = ['SPY', 'QQQ', 'IWM', 'FEZ', 'EWU', 'EWJ', 'FXI', 'GXC', 'EPI', 'FLIN', 'EWT', 'EWH', 'VWO', 'EEM']
T = [ x + ' US Equity' for x in T0]
F = ['name','currency','exch_code','undl_spot_ticker','beta_override_rel_index']
List = blp.bdp(tickers=T, flds=F).loc[T,:]

def f(T):
    tmp = []
    for i in range(len(T)):
        tmp  += [(blp.bdh(T[i], 'px_last', '19991201', '20240101', Per='Q').reset_index().iloc[0,0]).strftime('%Y%m')]
    return tmp


List['StartDate'] = ['-' if x == '199912' else x for x in f(T)]
List

,name,currency,exch_code,beta_override_rel_index,StartDate
SPY US Equity,SPDR S&P 500 ETF TRUST,USD,US,SPXT Index,-
QQQ US Equity,INVESCO QQQ TRUST SERIES 1,USD,US,XNDX Index,-
IWM US Equity,ISHARES RUSSELL 2000 ETF,USD,US,RU20INTR Index,200006
FEZ US Equity,SPDR EURO STOXX 50 ETF,USD,US,SX5U Index,200212
EWU US Equity,ISHARES MSCI UNITED KINGDOM,USD,US,NDDUUKR Index,-
EWJ US Equity,ISHARES MSCI JAPAN ETF,USD,US,NDDUJN Index,-
FXI US Equity,ISHARES CHINA LARGE-CAP ETF,USD,US,TXIN0UNU Index,200412
GXC US Equity,SPDR S&P CHINA ETF,USD,US,SCNUN Index,200703
EPI US Equity,WISDOMTREE INDIA EARNINGS,USD,US,WTEMINTR Index,200803
FLIN US Equity,FRANKLIN FTSE INDIA ETF,USD,US,FTINDN Index,201803
EWT US Equity,ISHARES MSCI TAIWAN ETF,USD,US,M1CXBISD Index,200006
EWH US Equity,ISHARES MSCI HONG KONG ETF,USD,US,NU730026 Index,-
VWO US Equity,VANGUARD FTSE EMERGING MARKE,USD,US,FQEACR Index,200503
EEM US Equity,ISHARES MSCI EMERGING MARKET,USD,US,NDUEEGF Index,200306

In [88]:
start_date = '2022-01-01'
ticker = T0[0]
tmp = yf.Ticker(ticker).history(start=start_date)
print('Net Div', round(sum(tmp['Dividends']),2) )
display(tmp.tail())

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Capital Gains
Date,,,,,,,,
2024-11-18 00:00:00-05:00,586.219971,589.489990,585.340027,588.150024,37084100,0.0,0.0,0.0
2024-11-19 00:00:00-05:00,584.710022,591.039978,584.030029,590.299988,49412000,0.0,0.0,0.0
2024-11-20 00:00:00-05:00,590.380005,590.789978,584.630005,590.500000,50032600,0.0,0.0,0.0
2024-11-21 00:00:00-05:00,593.400024,595.119995,587.450012,593.669983,46750300,0.0,0.0,0.0
2024-11-22 00:00:00-05:00,593.659973,596.150024,593.150024,595.510010,38092800,0.0,0.0,0.0

Net Div 18.05

In [127]:
start_date = '2022-01-01'
ticker = 'EURUSD=X'
ticker = 'JPY=X'
tmp = yf.Ticker(ticker).history(start=start_date)
print('Net Div', round(sum(tmp['Dividends']),2) )
display(tmp.tail())

Net Div 0.0

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-11-18 00:00:00+00:00,154.664001,155.339996,153.863998,154.664001,0,0.0,0.0
2024-11-19 00:00:00+00:00,154.617004,154.645004,153.397003,154.617004,0,0.0,0.0
2024-11-20 00:00:00+00:00,154.718002,155.871994,154.612000,154.718002,0,0.0,0.0
2024-11-21 00:00:00+00:00,155.294998,155.270004,153.951996,155.294998,0,0.0,0.0
2024-11-22 00:00:00+00:00,154.218002,154.979004,153.975006,154.218002,0,0.0,0.0

In [90]:
msci_tickers = {
    'MSCI_World_PR': 'MXWO.L',      # Price Return
    'MSCI_World_TR': 'NDDUWI',      # Total Return
    
    'MSCI_EMU_PR': 'MXEM.L',        # Price Return
    'MSCI_EMU_TR': 'NDDLEMU',       # Total Return
    
    'MSCI_EM_PR': 'MXEF.L',         # Price Return
    'MSCI_EM_TR': 'NDUEEGF',        # Total Return
}

msci_tickers

{'MSCI_World_PR': 'MXWO.L',
 'MSCI_World_TR': 'NDDUWI',
 'MSCI_EMU_PR': 'MXEM.L',
 'MSCI_EMU_TR': 'NDDLEMU',
 'MSCI_EM_PR': 'MXEF.L',
 'MSCI_EM_TR': 'NDUEEGF'}

In [92]:


df = pd.DataFrame({
    'Ticker': ['MXWO.L', 'NDDUWI', 'MXEM.L', 'NDDLEMU', 'MXEF.L', 'NDUEEGF'],
    'Index': ['World', 'World', 'EMU', 'EMU', 'EM', 'EM'],
    'Type': ['Price Return', 'Total Return', 'Price Return', 'Total Return', 'Price Return', 'Total Return'],
    'Description': [
        'MSCI World Price Return Index',
        'MSCI World Total Return Index',
        'MSCI EMU Price Return Index',
        'MSCI EMU Total Return Index',
        'MSCI Emerging Markets Price Return Index',
        'MSCI Emerging Markets Total Return Index'
    ]
})

df

    Ticker  Index          Type                               Description
0   MXWO.L  World  Price Return             MSCI World Price Return Index
1   NDDUWI  World  Total Return             MSCI World Total Return Index
2   MXEM.L    EMU  Price Return               MSCI EMU Price Return Index
3  NDDLEMU    EMU  Total Return               MSCI EMU Total Return Index
4   MXEF.L     EM  Price Return  MSCI Emerging Markets Price Return Index
5  NDUEEGF     EM  Total Return  MSCI Emerging Markets Total Return Index

In [125]:
tickers = {
    # US Indices
    'S&P500_PR': '^GSPC',           # Price Return
    'S&P500_TR': '^SP500TR',        # Total Return
    'Nasdaq100_PR': '^NDX',
    'DowJones_PR': '^DJI',
    'Russell2000': '^RUT',

    # European Indices
    'EURO_STOXX50_PR': '^STOXX50E',
    'DAX_PR': '^GDAXI',            
    'FTSE100_PR': '^FTSE', 
    
    # Asian Indices
    'Nikkei225_PR': '^N225',
    'TOPIX_PR': '1692.T',
    # Global Indices
    'NDDUWI': 'MXWO.L',         # World    
    'NDDUUS': 'MXUS.L',         # USA
    'NDDUJN': 'MXJP.L',         # Japan
}



start_date = '2022-01-01'
end_date = '2023-10-01'


historical_data = {}

for name, ticker in tickers.items():
    print(f"Fetching data for {name}...")
    index = yf.Ticker(ticker)
    df = index.history(start=start_date, end=end_date)
    df.reset_index(inplace=True)
    historical_data[name] = df
    print(f"Data for {name} fetched successfully.\n")

Fetching data for S&P500_PR...
Data for S&P500_PR fetched successfully.

Fetching data for S&P500_TR...
Data for S&P500_TR fetched successfully.

Fetching data for Nasdaq100_PR...
Data for Nasdaq100_PR fetched successfully.

Fetching data for DowJones_PR...
Data for DowJones_PR fetched successfully.

Fetching data for Russell2000...
Data for Russell2000 fetched successfully.

Fetching data for EURO_STOXX50_PR...
Data for EURO_STOXX50_PR fetched successfully.

Fetching data for DAX_PR...
Data for DAX_PR fetched successfully.

Fetching data for DAX_TR...
Data for DAX_TR fetched successfully.

Fetching data for FTSE100_PR...
Data for FTSE100_PR fetched successfully.

Fetching data for Nikkei225_PR...
Data for Nikkei225_PR fetched successfully.

Fetching data for TOPIX_PR...
Data for TOPIX_PR fetched successfully.

Fetching data for NDDUWI...
Data for NDDUWI fetched successfully.

Fetching data for NDDUUS...
Data for NDDUUS fetched successfully.

Fetching data for NDDUJN...
Data for NDDUJN fetched successfully.

In [128]:
import yfinance as yf
import pandas as pd
import pandas_datareader.data as web
from datetime import datetime

def get_fx_rates(currencies, start_date='2010-01-01'):
    """
    Get FX rates at NY close
    currencies: list of currency pairs (e.g., ['EURUSD', 'GBPUSD', 'JPYUSD'])
    """
    
    # Method 1: Using yfinance
    fx_data = pd.DataFrame()
    
    for curr in currencies:
        # Format for yfinance (add '=X' suffix)
        ticker = f"{curr}=X"
        data = yf.download(ticker, start=start_date)['Close']
        fx_data[curr] = data
        
    return fx_data

# Example usage
currencies = [
    'EURUSD',  # Euro
    'GBPUSD',  # British Pound
    'JPYUSD',  # Japanese Yen
    'CHFUSD',  # Swiss Franc
    'AUDUSD',  # Australian Dollar
    'CADUSD',  # Canadian Dollar
    'NZDUSD',  # New Zealand Dollar
    'SEKUSD',  # Swedish Krona
    'NOKUSD',  # Norwegian Krone
    'DKKUSD',  # Danish Krone
    
    # Emerging Market Currencies
    'CNYUSD',  # Chinese Yuan
    'INRUSD',  # Indian Rupee
    'KRWUSD',  # Korean Won
    'TWDUSD',  # Taiwan Dollar
    'BRLUSD',  # Brazilian Real
    'MXNUSD',  # Mexican Peso
    'RUBUSD',  # Russian Ruble
    'ZARUSD'   # South African Rand
]

# Get FX rates
fx_rates = get_fx_rates(currencies)

# Alternative Method using FRED (Federal Reserve Economic Data)
def get_fx_rates_fred(currencies, start_date='2010-01-01'):
    fx_data = pd.DataFrame()
    
    # FRED currency codes (example)
    fred_codes = {
        'EURUSD': 'DEXUSEU',
        'GBPUSD': 'DEXUSUK',
        'JPYUSD': 'DEXJPUS',
        # Add more as needed
    }
    
    for curr in currencies:
        if curr in fred_codes:
            data = web.DataReader(fred_codes[curr], 'fred', start_date)
            fx_data[curr] = 1 / data  # Convert to USD terms
    
    return fx_data

# Print results
print("\nFX Rates (Last 5 days):")
print(fx_rates.tail())

# Calculate returns
fx_returns = fx_rates.pct_change()

# Basic statistics
stats = pd.DataFrame({
    'Mean Return': fx_returns.mean() * 252,
    'Volatility': fx_returns.std() * np.sqrt(252),
    'Skewness': fx_returns.skew(),
    'Kurtosis': fx_returns.kurtosis()
})

print("\nFX Statistics:")
print(stats)

# Save to CSV
fx_rates.to_csv('fx_rates.csv')

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

FX Rates (Last 5 days):
              EURUSD    GBPUSD    JPYUSD    CHFUSD    AUDUSD    CADUSD  \
Date
2024-11-18  1.053375  1.261766  0.006466  1.125277  0.646341  0.709930
2024-11-19  1.059490  1.267925  0.006468  1.132246  0.650590  0.713145
2024-11-20  1.060760  1.269454  0.006463  1.133697  0.654150  0.716589
2024-11-21  1.054619  1.265534  0.006439  1.131670  0.651400  0.715922
2024-11-22  1.046934  1.258479  0.006484  1.127523  0.651029  0.715308

              NZDUSD    SEKUSD    NOKUSD    DKKUSD    CNYUSD    INRUSD  \
Date
2024-11-18  0.586321  0.091083  0.090237  0.141235  0.138293  0.011837
2024-11-19  0.589070  0.091776  0.090919  0.142043  0.138209  0.011849
2024-11-20  0.591961  0.091682  0.091282  0.142206  0.138158  0.011849
2024-11-21  0.588400  0.090727  0.090407  0.141385  0.138045  0.011851
2024-11-22  0.585741  0.090391  0.090313  0.140365  0.138242  0.011836

              KRWUSD    TWDUSD    BRLUSD    MXNUSD    RUBUSD    ZARUSD
Date
2024-11-18  0.000717  0.030805  0.172574  0.049125  0.010002  0.055046
2024-11-19  0.000720  0.030824  0.174022  0.049472  0.010025  0.055747
2024-11-20  0.000718  0.030935  0.173256  0.049727  0.009943  0.055474
2024-11-21  0.000716  0.030796  0.173289  0.049323  0.009941  0.055221
2024-11-22  0.000714  0.030764  0.171996  0.048986  0.009872  0.055257

FX Statistics:
        Mean Return  Volatility   Skewness     Kurtosis
EURUSD    -0.017011    0.085404  -0.045243     2.220792
GBPUSD    -0.012205    0.088496  -0.724632    11.755232
JPYUSD    -0.028678    0.091947   0.130526     3.922680
CHFUSD     0.014993    0.101537   6.444273   221.986905
AUDUSD    -0.015327    0.105762  -0.109714     1.643352
CADUSD    -0.015640    0.075849  -0.074738     2.349993
NZDUSD    -0.007813    0.109471  -0.090788     1.594341
SEKUSD    -0.022898    0.110477  -0.149130     1.776392
NOKUSD    -0.024689    0.187015   3.373296   509.910639
DKKUSD    -0.017421    0.085107  -0.043343     2.188347
CNYUSD    -0.002328    0.055279   0.735995   295.383099
INRUSD    -0.035661    0.077032   0.080979    25.530060
KRWUSD    -0.006607    0.112928   0.000422     4.950796
TWDUSD     1.364070    4.335825  49.933113  2637.408571
BRLUSD    -0.064644    0.170315   0.021977     3.475789
MXNUSD    -0.021460    0.122319  -0.699136     5.843231
RUBUSD     7.365893   26.020871  60.627467  3730.329907
ZARUSD    -0.044538    0.167959   0.986682    76.734344

C:\Users\ky090\AppData\Local\Temp\ipykernel_3688\4265609011.py:74: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  fx_returns = fx_rates.pct_change()