In [34]:
from xbbg import blp
def BDP(T):

    F = ['etf_undl_index_ticker','crncy','name_kanji','fund_management_co','fund_total_assets','fund_assets_usd','fund_expense_ratio','fund_total_exp']
    df = blp.bdp(tickers=T, flds=F).loc[T,:].reset_index(drop=False)
    df.rename(columns={'index': 'ticker'}, inplace=True)

    df = df.sort_values(by='fund_assets_usd', ascending=False).reset_index(drop=True)
    tmp = ['fund_total_assets','fund_assets_usd']
    df[tmp] = df[tmp].applymap('{:,.0f}'.format)
    
    tmp = list(dict.fromkeys(df['etf_undl_index_ticker'].tolist()))
    T = [x + ' Index' for x in tmp]
    BM = blp.bdp(tickers=T, flds=['name_kanji','long_comp_name']).loc[T,:].reset_index(drop=False)
    BM.rename(columns={'index': 'ticker'}, inplace=True)

    return df, BM

### Topix

In [35]:
T0 = ['1306','1308','1305','1348','1475','1473','2524']
T = [x + ' JP Equity' for x in T0] 
df, BM = BDP(T)
print('ETF')
display(df)
print('BM')
BM

ETF

,ticker,etf_undl_index_ticker,crncy,name_kanji,fund_management_co,fund_total_assets,fund_assets_usd,fund_expense_ratio,fund_total_exp
0,1306 JP Equity,TPX,JPY,NF・TOPIX ETF,Nomura Asset Management Co Ltd,"22,414,910","156,245",0.0536,0.0536
1,1308 JP Equity,TPX,JPY,上場ｲﾝﾃﾞｯｸｽﾌｧﾝﾄﾞTOPIX,Nikko Asset Management Co Ltd,"10,724,705","74,757",0.053,0.053
2,1305 JP Equity,TPX,JPY,iFreeETF TOPIX（年1回決算型),Daiwa Asset Management Co Ltd,"10,163,790","70,848",0.06,0.06
3,1348 JP Equity,TPX,JPY,MAXIS ﾄﾋﾟｯｸｽ上場投信,Mitsubishi UFJ Asset Management Co Ltd,"3,242,908","22,605",0.078,0.078
4,1475 JP Equity,TPXDDVD,JPY,iｼｪｱｰｽﾞ TOPIX ETF,BlackRock Japan Co Ltd,"1,708,634","11,910",0.045,0.045
5,1473 JP Equity,TPX,JPY,Ｏｎｅ ＥＴＦ トピックス,Asset Management One Co Ltd,"562,851","3,923",0.078,0.078
6,2524 JP Equity,TPX,JPY,NZAM 上場投信 TOPIX,Norinchukin Zenkyoren Asset Management Co Ltd,"243,894","1,700",0.075,0.075

BM

,ticker,name_kanji,long_comp_name
0,TPX Index,TOPIX (東証株価指数),Tokyo Stock Exchange Tokyo Stock Price Index T...
1,TPXDDVD Index,TOPIX 配当込み株価指数,Topix Total Return Index JPY

### Global Equities (ACWI)
1. VTI + VEA + VWO
2. VTI + VXUS
3. VT
4. 2559 *low liquidity


WealthNavi\
https://www.wealthnavi.com/image/WealthNavi_WhitePaper.pdf?v=20231004

Susten\
https://susten.jp/fund/

In [61]:
T0 = ['ACWI US','ISAC LN','ACWD LN','2559 JP','1554 JP','VT US']
T = [x + ' Equity' for x in T0] 
df, BM = BDP(T)
print('ETF')
display(df)
print('BM')
BM

ETF

,ticker,etf_undl_index_ticker,crncy,name_kanji,fund_management_co,fund_total_assets,fund_assets_usd,fund_expense_ratio,fund_total_exp
0,VT US Equity,TGPVA16U,USD,ﾊﾞﾝｶﾞｰﾄﾞ･ﾄｰﾀﾙ･ﾜｰﾙﾄﾞ･ｽﾄｯｸETF,Vanguard Group Inc/The,"40,693","40,693",0.07,0.07
1,ACWI US Equity,NDUEACWF,USD,iｼｪｱｰｽﾞMSCI ACWI ETF,BlackRock Fund Advisors,"19,280","19,280",0.32,0.32
2,ISAC LN Equity,NDUEACWF,USD,iｼｪｱｰｽﾞMSCI ACWI UCITS ETF U,BlackRock Asset Management Ireland Ltd,"16,337","16,337",0.2,0.2
3,ACWD LN Equity,NDUEACWF,USD,SPDR MSCI ACWI UCITS ETF,State Street Global Advisors Europe Ltd,"3,509","3,509",0.12,0.12
4,2559 JP Equity,MXWD,JPY,MAXIS全世界株式(ｵｰﾙ･ｶﾝﾄﾘｰ)上,Mitsubishi UFJ Asset Management Co Ltd,"55,205",385,0.078,0.078
5,1554 JP Equity,MXWDJ,JPY,上場ｲﾝﾃﾞｯｸｽﾌｧﾝﾄﾞ世界株式(MSC,Nikko Asset Management Co Ltd,"11,804",82,0.24,0.24

BM

,ticker,name_kanji,long_comp_name
0,TGPVA16U Index,FTSE GPVAN016 USD NTR,FTSE Global All Cap Net Tax (US RIC) Index
1,NDUEACWF Index,MSCI AC World Daily TR N,MSCI ACWI Net Total Return USD Index
2,MXWD Index,MSCI ACWI Index,MSCI ACWI Index
3,MXWDJ Index,MSCI ACWI ex Japan Index,MSCI ACWI ex Japan Index

In [62]:
T0 = ['SPY','VTI','VOO','IVV','SPLG']
T = [x + ' US Equity' for x in T0] 
df, BM = BDP(T)
print('ETF')
display(df)
print('BM')
BM

ETF

,ticker,etf_undl_index_ticker,crncy,name_kanji,fund_management_co,fund_total_assets,fund_assets_usd,fund_expense_ratio,fund_total_exp
0,SPY US Equity,SPXT,USD,SPDR S&P500 ETFﾄﾗｽﾄ,SSgA Funds Management Inc,"582,958","582,958",0.0945,0.0945
1,VOO US Equity,SPTR,USD,ﾊﾞﾝｶﾞｰﾄﾞS&P500ETF,Vanguard Group Inc/The,"542,685","542,685",0.03,0.03
2,IVV US Equity,SPTR,USD,iｼｪｱｰｽﾞS&P500 ETF,BlackRock Fund Advisors,"504,064","504,064",0.03,0.03
3,VTI US Equity,CRSPTMT,USD,ﾊﾞﾝｶﾞｰﾄﾞ･ﾄｰﾀﾙ･ｽﾄｯｸ･ﾏｰｹｯﾄETF,Vanguard Group Inc/The,"439,913","439,913",0.03,0.03
4,SPLG US Equity,SPXT,USD,SPDR Portfolio S&P 500 ETF,SSgA Funds Management Inc,"45,904","45,904",0.02,0.02

BM

,ticker,name_kanji,long_comp_name
0,SPXT Index,S&P 500 Total Return Index,S&P 500 Total Return Index
1,SPTR Index,S&P 500 TR 4 JAN 1988,S&P 500 Total Return 4 JAN 1988 Index
2,CRSPTMT Index,CRSP US Total Market TR Index,CRSP US Total Market TR Index

In [46]:
# ex US
T0 = ['VEA US','VXUS US','VEU US','IXUS US', 'ACWX US', 'CWI US']
T = [x + ' Equity' for x in T0] 
df, BM = BDP(T)
print('ETF')
display(df)
print('BM')
BM

ETF

,ticker,etf_undl_index_ticker,crncy,name_kanji,fund_management_co,fund_total_assets,fund_assets_usd,fund_expense_ratio,fund_total_exp
0,VEA US Equity,ACDXUSR,USD,ﾊﾞﾝｶﾞｰﾄﾞ FTSEﾃﾞｨﾍﾞﾛｯﾌﾟﾄﾞ･ﾏｰｹ,Vanguard Group Inc/The,"142,489","142,489",0.06,0.06
1,VXUS US Equity,TGPVAN17,USD,ﾊﾞﾝｶﾞｰﾄﾞ･ﾄｰﾀﾙ･ｲﾝﾀｰﾅｼｮﾅﾙ･ｽﾄｯｸ,Vanguard Group Inc/The,"78,252","78,252",0.08,0.08
2,VEU US Equity,AWXUSRUS,USD,ﾊﾞﾝｶﾞｰﾄﾞFTSEｵｰﾙﾜｰﾙﾄﾞ除米国ET,Vanguard Group Inc/The,"40,913","40,913",0.07,0.07
3,IXUS US Equity,M1WDUIM,USD,iｼｪｱｰｽﾞ･ｺｱMSCI ﾄｰﾀﾙ･ｲﾝﾀｰﾅｼｮﾅ,BlackRock Fund Advisors,"38,996","38,996",0.07,0.07
4,ACWX US Equity,NDUEACWZ,USD,iｼｪｱｰｽﾞMSCI ACWI(除米国)ETF,BlackRock Fund Advisors,"4,702","4,702",0.34,0.34
5,CWI US Equity,M1WDU,USD,SPDR MSCI全世界株式(除く米国,SSgA Funds Management Inc,"1,659","1,659",0.3,0.3

BM

,ticker,name_kanji,long_comp_name
0,ACDXUSR Index,FTSE DvXUSAllCapNTxUSRIC,FTSE Developed ex US All Cap Net Tax (US RIC) ...
1,TGPVAN17 Index,FTSE GPVAN017 $ TR,FTSE Global ex US All Cap Net Tax (US RIC) Index
2,AWXUSRUS Index,FTSE AllWorld exUSNUS RI,FTSE All World ex US Net Tax (US RIC) Index
3,M1WDUIM Index,MSCI ACWI ex USA IMI NR,MSCI ACWI ex USA IMI Net Total Return USD Index
4,NDUEACWZ Index,MSCI AC World ExUS NTR,MSCI ACWI ex USA Net Total Return USD Index
5,M1WDU Index,MSCI AC WORLD ex USA NR,MSCI ACWI ex USA Net Total Return USD Index

In [47]:
T0 = ['VWO US','IEMG US','EEM US','VFEA LN']
T = [x + ' Equity' for x in T0] 
df, BM = BDP(T)
print('ETF')
display(df)
print('BM')
BM

ETF

,ticker,etf_undl_index_ticker,crncy,name_kanji,fund_management_co,fund_total_assets,fund_assets_usd,fund_expense_ratio,fund_total_exp
0,VWO US Equity,FQEACR,USD,ﾊﾞﾝｶﾞｰﾄﾞFTSEｴﾏｰｼﾞﾝｸﾞ･ﾏｰｹｯﾂET,Vanguard Group Inc/The,"82,338","82,338",0.08,0.08
1,IEMG US Equity,MIMUEMRN,USD,iｼｪｱｰｽﾞ･ｺｱMSCIｴﾏｰｼﾞﾝｸﾞ･ﾏｰｹｯﾄ,BlackRock Fund Advisors,"81,128","81,128",0.09,0.09
2,EEM US Equity,NDUEEGF,USD,iｼｪｱｰｽﾞMSCIｴﾏｰｼﾞﾝｸﾞ･ﾏｰｹｯﾄETF,BlackRock Fund Advisors,"17,930","17,930",0.7,0.7
3,VFEA LN Equity,TAWALENU,USD,ﾊﾞﾝｶﾞｰﾄﾞFTSEｴﾏｰｼﾞﾝｸﾞﾏｰｹｯﾂUCI,Vanguard Group Ireland Ltd,"3,075","3,075",0.22,0.22

BM

,ticker,name_kanji,long_comp_name
0,FQEACR Index,FTSE EmMarkAllCapChinA,FTSE Emerging Markets All Cap China A Inclusio...
1,MIMUEMRN Index,MSCI EM EMerging Markets,MSCI EM EMerging Markets IMI USD Net
2,NDUEEGF Index,MSCI Daily TR Net Emergi,MSCI Emerging Net Total Return USD Index
3,TAWALENU Index,FTSE Emerging Net TaxTR$,FTSE Emerging Net Tax Index TR USD

In [48]:
ISO = blp.bds('ACWI US Equity','LU_COUNTRY_ISO').reset_index(drop=True) 
ISO.columns = ['ISO','Name']

BBG = blp.bds('ACWI US Equity','LU_CDR_COUNTRY_CODE').reset_index(drop=True)
BBG.columns = ['BBG','Name']
BBG['Name'] = BBG['Name'].str.upper()

Mapping = BBG.set_index('Name')['BBG'].to_dict()
ISO.insert(1, 'BBG',0)
ISO['BBG'] = ISO['Name'].map(Mapping).fillna(ISO['ISO'])

W = blp.bds('ACWI US Equity','HB_GEO_CNTRY_ALLOC')
W.columns = ['Name', 'Weight']
W = W.sort_values(by='Weight', ascending=False).reset_index(drop=True)
W.insert(0, 'ISO',0)
W.insert(1, 'BBG',0)
tmp = W['Name']
W['Name'] = W['Name'].str.upper()

Mapping = ISO.set_index('Name')['ISO'].to_dict()
Mapping.update({'U.S.': 'US', 'U.K.': 'GB','Czech Republic': 'CZ','U.A.E.': 'AE'} )
W['ISO'] = W['Name'].map(Mapping).fillna(W['ISO'])

Mapping = ISO.set_index('Name')['BBG'].to_dict()
Mapping.update({'U.S.': 'US', 'U.K.': 'GB'} )
W['BBG'] = W['Name'].map(Mapping).fillna(W['BBG'])

W['Name'] = tmp
W['Weight']  = round(W['Weight'],2)
W['Cumulative'] = W['Weight'].cumsum()
W.loc[:19,:]

   ISO BBG         Name  Weight  Cumulative
0   US  US         U.S.   62.91       62.91
1   JP  JN        Japan    5.03       67.94
2   GB  GB         U.K.    3.23       71.17
3   CA  CA       Canada    2.85       74.02
4   CH  SZ  Switzerland    2.51       76.53
5   FR  FR       France    2.47       79.00
6   CN  CH        China    2.41       81.41
7   IN  IN        India    2.06       83.47
8   DE  GE      Germany    1.99       85.46
9   TW  TA       Taiwan    1.90       87.36
10  AU  AU    Australia    1.70       89.06
11  NL  NE  Netherlands    1.21       90.27
12  KR  KR  South Korea    1.11       91.38
13  IE  IR      Ireland    0.94       92.32
14  DK  DE      Denmark    0.80       93.12
15  SE  SW       Sweden    0.74       93.86
16  ES  SP        Spain    0.62       94.48
17  HK  HK    Hong Kong    0.59       95.07
18  IT  IT        Italy    0.56       95.63
19  BR  BZ       Brazil    0.52       96.15

### Bond
Govt + IGOV\
国債のみ&中国除きだが、流動性が低い


AGG + IAGG\
世界の主流だが、社債と中国を含む (or BND + BNDX)

In [65]:
T0 = ['GOVT US','IGOV US','FLQA LN','HGVU LN','1677 JP','2511 JP','AGG US','IAGG US','EMB US','GLAG LN','BND US','BNDX US','VGIT US']
T = [x + ' Equity' for x in T0] 
df, BM = BDP(T)
print('ETF')
display(df)
print('BM')
BM

ETF

,ticker,etf_undl_index_ticker,crncy,name_kanji,fund_management_co,fund_total_assets,fund_assets_usd,fund_expense_ratio,fund_total_exp
0,AGG US Equity,LBUSTRUU,USD,iｼｪｱｰｽﾞ･ｺｱ 米国総合債券市場E,BlackRock Fund Advisors,"120,996","120,996",0.03,0.03
1,BND US Equity,LBUFTRUU,USD,ﾊﾞﾝｶﾞｰﾄﾞ･ﾄｰﾀﾙ債券市場ETF,Vanguard Group Inc/The,"118,878","118,878",0.03,0.03
2,BNDX US Equity,BGRCTRUH,USD,ﾊﾞﾝｶﾞｰﾄﾞ･ﾄｰﾀﾙ･ｲﾝﾀｰﾅｼｮﾅﾙ債券E,Vanguard Group Inc/The,"60,368","60,368",0.07,0.07
3,VGIT US Equity,LT31TRUU,USD,ﾊﾞﾝｶﾞｰﾄﾞ米国中期国債ETF,Vanguard Group Inc/The,"30,921","30,921",0.04,0.04
4,GOVT US Equity,IDCOTC,USD,iｼｪｱｰｽﾞ･ｺｱ米国債ETF,BlackRock Fund Advisors,"27,918","27,918",0.05,0.05
5,EMB US Equity,JPEICORE,USD,iｼｪｱｰｽﾞJPﾓﾙｶﾞﾝ･米ﾄﾞﾙ建てｴﾏｰｼ,BlackRock Fund Advisors,"16,145","16,145",0.39,0.39
6,HGVU LN Equity,SBWGU,USD,HSBC Global Funds ICAV - Glo,HSBC Investment Funds Luxembourg SA/Luxembourg,"7,475","7,475",0.22,0.22
7,IAGG US Equity,B10CTRUH,USD,iShares Core International A,BlackRock Fund Advisors,"6,950","6,950",0.07,0.07
8,GLAG LN Equity,LEGATRUU,USD,SPDR Bloomberg Global Aggreg,State Street Global Advisors Ltd/United Kingdom,"3,844","3,844",0.1,0.1
9,IGOV US Equity,CFIIWDCS,USD,iｼｪｱｰｽﾞ世界国債ETF,BlackRock Fund Advisors,530,530,0.35,0.35
10,2511 JP Equity,SBWGNJYU,JPY,NF・外国債ヘッジ無ETF,Nomura Asset Management Co Ltd,"42,291",295,0.12,0.12
11,1677 JP Equity,SBWJNJYU,JPY,上場ｲﾝﾃﾞｯｸｽﾌｧﾝﾄﾞ海外債券(FTS,Nikko Asset Management Co Ltd,"31,376",219,0.25,0.25
12,FLQA LN Equity,AWAPXJCN,USD,Franklin FTSE Asia ex China,Franklin Templeton International Services Sarl,78,78,0.14,0.14

BM

,ticker,name_kanji,long_comp_name
0,LBUSTRUU Index,BBG米国総合TRﾊﾞﾘｭｰUhd(USD),Bloomberg US Agg Total Return Value Unhedged USD
1,LBUFTRUU Index,BBG米国総合浮動調整TR Idxﾊﾞﾘｭｰ,Bloomberg US Aggregate Float Adjusted Total Re...
2,BGRCTRUH Index,BBGGLA x米ﾄﾞﾙ浮動債調整後RICｷｬ,Bloomberg GLA xUSD Float Adj RIC Capped Index ...
3,LT31TRUU Index,ﾌﾞﾙｰﾑﾊﾞｰｸﾞ米国債3-10年TRｲﾝﾃﾞｯｸ,Bloomberg U.S. Treasury 3-10 Year Total Return...
4,IDCOTC Index,UST Core,ICE US Treasury Core Bond Index
5,JPEICORE Index,J.P. Morgan EMBI Global Core,J.P. Morgan EMBI Global Core
6,SBWGU Index,FTSE世界国債ｲﾝﾃﾞｯｸｽ(WGBI)USD,FTSE World Government Bond Index (WGBI) USD
7,B10CTRUH Index,Bloomberg GLA ex USD 10% Issue,Bloomberg GLA ex USD 10% Issuer Cap Total Retu...
8,LEGATRUU Index,BBGｸﾞﾛｰﾊﾞﾙ総合TR Indxﾊﾞﾘｭｰﾍｯｼﾞ,Bloomberg Global-Aggregate Total Return Index ...
9,CFIIWDCS Index,World Gov Bond,World Government Bond Index - Developed Market...
10,SBWGNJYU Index,FTSE Non-JPY WGBI JPY,FTSE Non-JPY WGBI JPY
11,SBWJNJYU Index,WGBI - JP Inv Trust,FTSE Non-JPY WGBI - Japan Investment Trust JPY
12,AWAPXJCN Index,FTSE Asia ex Japan ex Ch,FTSE Asia ex Japan ex China Net Tax Index USD