In [1]:
from xbbg import blp
import pandas as pd
# https://www.msci.com/www/product-documentation/bloomberg-ticker-list/0163827567

In [2]:
ISO = blp.bds('ACWI US Equity','LU_COUNTRY_ISO').reset_index(drop=True) 
ISO.columns = ['ISO','Name']

BBG = blp.bds('ACWI US Equity','LU_CDR_COUNTRY_CODE').reset_index(drop=True)
BBG.columns = ['BBG','Name']
BBG['Name'] = BBG['Name'].str.upper()

Mapping = BBG.set_index('Name')['BBG'].to_dict()
ISO.insert(1, 'BBG',0)
ISO['BBG'] = ISO['Name'].map(Mapping).fillna(ISO['ISO'])

W = blp.bds('ACWI US Equity','HB_GEO_CNTRY_ALLOC')
W.columns = ['Name', 'Weight']
W = W.sort_values(by='Weight', ascending=False).reset_index(drop=True)
W.insert(0, 'ISO',0)
W.insert(1, 'BBG',0)
tmp = W['Name']
W['Name'] = W['Name'].str.upper()

Mapping = ISO.set_index('Name')['ISO'].to_dict()
Mapping.update({'U.S.': 'US', 'U.K.': 'GB','Czech Republic': 'CZ','U.A.E.': 'AE'} )
W['ISO'] = W['Name'].map(Mapping).fillna(W['ISO'])

Mapping = ISO.set_index('Name')['BBG'].to_dict()
Mapping.update({'U.S.': 'US', 'U.K.': 'GB'} )
W['BBG'] = W['Name'].map(Mapping).fillna(W['BBG'])

W['Name'] = tmp
W['Weight']  = round(W['Weight'],2)
W.loc[:19,:]

   ISO BBG         Name  Weight
0   US  US         U.S.   61.85
1   JP  JN        Japan    5.26
2   GB  GB         U.K.    3.37
3   CA  CA       Canada    2.78
4   FR  FR       France    2.73
5   CN  CH        China    2.58
6   CH  SZ  Switzerland    2.52
7   DE  GE      Germany    1.99
8   TW  TA       Taiwan    1.80
9   IN  IN        India    1.78
10  AU  AU    Australia    1.69
11  NL  NE  Netherlands    1.34
12  KR  KR  South Korea    1.25
13  IE  IR      Ireland    1.06
14  DK  DE      Denmark    0.86
15  SE  SW       Sweden    0.72
16  HK  HK    Hong Kong    0.67
17  ES  SP        Spain    0.64
18  IT  IT        Italy    0.58
19  BR  BZ       Brazil    0.50

In [3]:
data = [
    ['MXWD', 'M2WD', 'M1WD', '-', '-', '-'],
    ['MXWO', 'M2WO', 'M1WO', '-', '-', '-'],
    ['MXEF', 'M2EF', 'M1EF', '-', '-', '-'],
    ['MXEU', 'M2EU', 'M1EU', '-', '-', '-'],
    ['MXUS', 'M2US', 'M1US', 'ES', 'SPX', 'SPXT'],
    ['MXJP', 'M8JP', 'M7JP', 'TP', 'TPX', 'TPXDDVD'],
    ['MXGB', 'M8GB', 'M7GB', 'Z', 'UKX', 'TUKXG'],
    ['MXCA', 'M8CA', 'M7CA', 'PT', 'SPTSX60', '-'],
    ['MXFR', 'M8FR', 'M7FR', 'CF', 'CAC', '-'],
    ['MXCN', 'M8CN', 'M7CN', 'IFB', 'SHSN300', '-'],
    ['MXCH', 'M8CH', 'M7CH', 'SM', 'SMI', '-'],
    ['MXDE', 'M8DE', 'M7DE', 'GX', 'DAX', '-'],
    ['TAMSCI', 'M8TW', 'M7TW', 'FT', 'TWSE', '-'],
    ['MXIN', 'M8IN', 'M7IN', 'NZ', 'NIFTY', '-'],
    ['MXAU', 'M8AU', 'M7AU', 'XP', 'AS51', '-'],
    ['MXNL', 'M8NL', 'M7NL', 'EO', 'AEX', '-'],
    ['MXKR', 'M8KR', 'M7KR', 'KM', 'KOSPI2', '-'],
    ['MXIE', 'M8IE', 'M7IE', '-', 'ISEQ', '-'],
    ['MXDK', 'M8DK', 'M7DK', 'OMW', 'OMXC25', '-'],
    ['MXSE', 'M8SE', 'M7SE', 'QC', 'OMX', '-'],
    ['MXHK', 'M8HK', 'M7HK', 'HI', 'HSI', '-'],
    ['MXES', 'M8ES', 'M7ES', 'IB', 'IBEX', '-'],
    ['MXIT', 'M8IT', 'M7IT', 'SW', 'FTSEMIB', '-'],
    ['MXBR', 'M2BR', 'M1BR', 'BZ', 'IBOV', '-']
]

df = pd.DataFrame(data, columns=['Price', 'Gross', 'Net', 'Future', 'Index', 'Index_Gross'])
tmp = [x + ' Index' for x in df['Price']]
Name = blp.bdp([x + ' Index' for x in df['Price']],['country_iso','name']).loc[tmp,:].reset_index(drop=True)

df = pd.concat([Name, df], axis=1)
df

,country_iso,name,Price,Gross,Net,Future,Index,Index_Gross
0,MULT,MSCI ACWI,MXWD,M2WD,M1WD,-,-,-
1,MULT,MSCI WORLD,MXWO,M2WO,M1WO,-,-,-
2,MULT,MSCI EM,MXEF,M2EF,M1EF,-,-,-
3,EU,MSCI EUROPE,MXEU,M2EU,M1EU,-,-,-
4,US,MSCI USA,MXUS,M2US,M1US,ES,SPX,SPXT
5,JP,MSCI JAPAN,MXJP,M8JP,M7JP,TP,TPX,TPXDDVD
6,GB,MSCI UK,MXGB,M8GB,M7GB,Z,UKX,TUKXG
7,CA,MSCI CANADA,MXCA,M8CA,M7CA,PT,SPTSX60,-
8,FR,MSCI FRANCE,MXFR,M8FR,M7FR,CF,CAC,-
9,MULT,MSCI CHINA,MXCN,M8CN,M7CN,IFB,SHSN300,-
10,CH,MSCI SWITZERLAND,MXCH,M8CH,M7CH,SM,SMI,-
11,DE,MSCI GERMANY,MXDE,M8DE,M7DE,GX,DAX,-
12,TW,MSCI TAIWAN,TAMSCI,M8TW,M7TW,FT,TWSE,-
13,IN,MSCI INDIA,MXIN,M8IN,M7IN,NZ,NIFTY,-
14,AU,MSCI AUSTRALIA,MXAU,M8AU,M7AU,XP,AS51,-
15,NL,MSCI NETHERLANDS,MXNL,M8NL,M7NL,EO,AEX,-
16,KR,MSCI KOREA,MXKR,M8KR,M7KR,KM,KOSPI2,-
17,IE,MSCI IRELAND,MXIE,M8IE,M7IE,-,ISEQ,-
18,DK,MSCI DENMARK,MXDK,M8DK,M7DK,OMW,OMXC25,-
19,SE,MSCI SWEDEN,MXSE,M8SE,M7SE,QC,OMX,-
20,HK,MSCI HONG KONG,MXHK,M8HK,M7HK,HI,HSI,-
21,ES,MSCI SPAIN,MXES,M8ES,M7ES,IB,IBEX,-
22,IT,MSCI ITALY,MXIT,M8IT,M7IT,SW,FTSEMIB,-
23,BR,MSCI BRAZIL,MXBR,M2BR,M1BR,BZ,IBOV,-