In [1]:
from xbbg import blp
import pdblp
import workdays
from datetime import datetime, timedelta, date
# https://pypi.org/project/xbbg/

In [2]:
d = workdays.workday(date.today(), days=0).strftime('%Y-%m-%d')
df = blp.bdib(ticker='ES1 Index', dt=d)
df

                          ES1 Index                                    \
                               open     high      low    close volume
2024-11-25 18:01:00-05:00   6015.00  6015.75  6014.50  6015.75    167
2024-11-25 18:02:00-05:00   6016.00  6017.25  6016.00  6017.00    332
2024-11-25 18:03:00-05:00   6017.00  6017.25  6016.25  6016.25    122
2024-11-25 18:04:00-05:00   6016.50  6017.50  6016.50  6017.25    107
2024-11-25 18:05:00-05:00   6017.00  6018.00  6016.75  6017.00    203
...                             ...      ...      ...      ...    ...
2024-11-26 00:46:00-05:00   6004.75  6005.00  6004.00  6004.25     71
2024-11-26 00:47:00-05:00   6004.00  6004.00  6003.50  6003.75    152
2024-11-26 00:48:00-05:00   6003.75  6003.75  6002.25  6002.75    401
2024-11-26 00:49:00-05:00   6002.75  6004.25  6002.50  6004.00    232
2024-11-26 00:50:00-05:00   6004.25  6004.50  6004.25  6004.25     41


                          num_trds       value
2024-11-25 18:01:00-05:00       99  1004523.25
2024-11-25 18:02:00-05:00      179  1997555.00
2024-11-25 18:03:00-05:00       66   734038.75
2024-11-25 18:04:00-05:00       54   643825.00
2024-11-25 18:05:00-05:00       74  1221516.00
...                            ...         ...
2024-11-26 00:46:00-05:00       36   426313.00
2024-11-26 00:47:00-05:00       70   912577.00
2024-11-26 00:48:00-05:00      141  2407128.00
2024-11-26 00:49:00-05:00       56  1392742.75
2024-11-26 00:50:00-05:00       24   246175.75

[410 rows x 7 columns]

In [3]:
d = workdays.workday(date.today(), days=-1).strftime('%Y-%m-%d')
df = blp.bdib(ticker='7974 JT Equity', dt=d, session='am_open_30')
df

                          7974 JT Equity                                 \
                                    open    high     low   close volume
2024-11-25 09:01:00+09:00         8216.0  8221.0  8205.0  8207.0  14200
2024-11-25 09:02:00+09:00         8207.0  8217.0  8204.0  8217.0  38100
2024-11-25 09:03:00+09:00         8218.0  8220.0  8189.0  8190.0  66000
2024-11-25 09:04:00+09:00         8189.0  8193.0  8181.0  8189.0  13100
2024-11-25 09:05:00+09:00         8192.0  8201.0  8192.0  8193.0  17500
2024-11-25 09:06:00+09:00         8192.0  8194.0  8177.0  8184.0  40200
2024-11-25 09:07:00+09:00         8184.0  8187.0  8177.0  8182.0   6800
2024-11-25 09:08:00+09:00         8181.0  8182.0  8177.0  8182.0   5400
2024-11-25 09:09:00+09:00         8181.0  8181.0  8171.0  8173.0   8900
2024-11-25 09:10:00+09:00         8173.0  8179.0  8167.0  8178.0  12800
2024-11-25 09:11:00+09:00         8179.0  8190.0  8178.0  8185.0  39100
2024-11-25 09:12:00+09:00         8183.0  8186.0  8180.0  8186.0  10400
2024-11-25 09:13:00+09:00         8187.0  8189.0  8187.0  8188.0   2600
2024-11-25 09:14:00+09:00         8188.0  8190.0  8185.0  8188.0   5900
2024-11-25 09:15:00+09:00         8190.0  8195.0  8190.0  8191.0  13100
2024-11-25 09:16:00+09:00         8193.0  8193.0  8173.0  8176.0  15100
2024-11-25 09:17:00+09:00         8177.0  8187.0  8177.0  8186.0  14800
2024-11-25 09:18:00+09:00         8188.0  8188.0  8183.0  8185.0   5800
2024-11-25 09:19:00+09:00         8184.0  8185.0  8178.0  8180.0   7400
2024-11-25 09:20:00+09:00         8180.0  8185.0  8175.0  8178.0   9900
2024-11-25 09:21:00+09:00         8179.0  8180.0  8168.0  8172.0   9900
2024-11-25 09:22:00+09:00         8172.0  8176.0  8172.0  8173.0   6500
2024-11-25 09:23:00+09:00         8176.0  8181.0  8176.0  8176.0  13300
2024-11-25 09:24:00+09:00         8178.0  8181.0  8177.0  8180.0   4900
2024-11-25 09:25:00+09:00         8180.0  8184.0  8177.0  8182.0  12200
2024-11-25 09:26:00+09:00         8183.0  8191.0  8183.0  8190.0  23100
2024-11-25 09:27:00+09:00         8189.0  8189.0  8182.0  8185.0   4500
2024-11-25 09:28:00+09:00         8186.0  8191.0  8180.0  8180.0   8400
2024-11-25 09:29:00+09:00         8181.0  8185.0  8180.0  8180.0   4000
2024-11-25 09:30:00+09:00         8182.0  8187.0  8176.0  8180.0  10500
2024-11-25 09:31:00+09:00         8181.0  8189.0  8181.0  8188.0  11200


                          num_trds        value
2024-11-25 09:01:00+09:00       70  116646096.0
2024-11-25 09:02:00+09:00       93  312833312.0
2024-11-25 09:03:00+09:00      124  541337472.0
2024-11-25 09:04:00+09:00       62  107251600.0
2024-11-25 09:05:00+09:00       73  143433600.0
2024-11-25 09:06:00+09:00      109  328936896.0
2024-11-25 09:07:00+09:00       44   55635400.0
2024-11-25 09:08:00+09:00       35   44171600.0
2024-11-25 09:09:00+09:00       43   72767296.0
2024-11-25 09:10:00+09:00       54  104629200.0
2024-11-25 09:11:00+09:00       94  320020000.0
2024-11-25 09:12:00+09:00       37   85110000.0
2024-11-25 09:13:00+09:00       16   21288600.0
2024-11-25 09:14:00+09:00       26   48306400.0
2024-11-25 09:15:00+09:00       52  107315800.0
2024-11-25 09:16:00+09:00       58  123614304.0
2024-11-25 09:17:00+09:00       46  121094600.0
2024-11-25 09:18:00+09:00       28   47476800.0
2024-11-25 09:19:00+09:00       51   60545200.0
2024-11-25 09:20:00+09:00       53   80980096.0
2024-11-25 09:21:00+09:00       49   80919904.0
2024-11-25 09:22:00+09:00       24   53132500.0
2024-11-25 09:23:00+09:00       56  108770304.0
2024-11-25 09:24:00+09:00       26   40074600.0
2024-11-25 09:25:00+09:00       59   99814096.0
2024-11-25 09:26:00+09:00       50  189134496.0
2024-11-25 09:27:00+09:00       20   36835100.0
2024-11-25 09:28:00+09:00       36   68772096.0
2024-11-25 09:29:00+09:00       27   32729300.0
2024-11-25 09:30:00+09:00       61   85916200.0
2024-11-25 09:31:00+09:00       47   91674704.0